# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Morris Animal Refuge
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Morris Animal Refuge is a 501(c)(3) open admission shelter 
  dedicated to helping the homeless, abandoned and unwanted pets of 
  the Philadelphia region.  Founded in 1874 by Elizabeth Morris, we 
  were the first organization dedicated to sheltering and rehoming 
  pets, and continue that legacy today by providing adoptions, a 
  low-cost spay/neuter program, fostering, humane education and 
  more.

domain: tatimblin.github.io
url: https://tatimblin.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog


twitter_username: MorrisAnimal
github_username:  tatimblin

# Build settings
markdown: kramdown
permalink: /product/:slug/

# SASS
sass:
  sass_dir: _sass
  style: compressed
